# Generated by Django 4.2.1 on 2023-05-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_ordermodel_bairro_ordermodel_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
